### PR TITLE
fix: update CI/CD process to enable auto-release workflow

### PR DESCRIPTION
**Pull request by bryantbiggs**
## Description
- add new hook to pre-commit to fix eof lines
- add new `release.yml` workflow. this workflow will automatically:
	- create and push new tag for next [semver based on conventional-commits](https://github.com/semantic-release/semantic-release#commit-message-format)
	- create GitHub release with notes
	- update Changelog with release notes
	- this workflow will also automatically notify PRs that are included in the release, mimicking the manual behavior but now its automated https://github.com/clowdhaus/terraform-aws-rds/pull/1#issuecomment-952097291
- remove old `chglog` configs and Makefile

## Motivation and Context
- automate release process in a standardized manner
- standardize new CI workflow (copying from RDS)

## Breaking Changes
- No

## How Has This Been Tested?
- [x] https://github.com/terraform-aws-modules/terraform-aws-rds/pull/361

### CODE REVIEW

**Comment by bryantbiggs** [comment]
@antonbabenko FYI - looks like the Semantic Pull Request isn't on this repo (also not sure if that is broken since it seems to be hanging lately on checks that are valid)

**Comment by antonbabenko** [comment]
"Semantic Pull Request" was deactivated on org-level and it has to be removed from all repos (I did it already on many).

**Comment by bryantbiggs** [comment]
ah ok

**Comment by antonbabenko** [comment]
Btw, is it possible to adjust this message - https://github.com/terraform-aws-modules/terraform-aws-s3-bucket/pull/116#issuecomment-962667053 ?

Let's wait a bit before copying to other repos. I have a few comments before rolling forward.

**Comment by bryantbiggs** [comment]
hmm, I don't know to be honest

**Comment by antonbabenko** [comment]
I have tried to fix the commit message in multiple PRs and I think it is good now - https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/pull/257

**Pull request merged**
