### PR TITLE
fix: Fixed the issue with ACLs configuration update

### PR DESCRIPTION
**Pull request by PavloPavlichenko**
## Description
Fix the issue with ACLs configuration update.

## Motivation and Context
In case you had `BucketOwnerEnforced `object ownership and you wanted to change it to `BucketOwnerPreferred` or `ObjectWriter` simultaneously adding ACLs - you run into the problem:
```
Error: error updating S3 bucket ACL (bucket-id): AccessControlListNotSupported: The bucket does not allow ACLs
```
In order to bypass this problem the `depends_on` block in `aws_s3_bucket_acl` resource is needed.

## Breaking Changes
No

## How Has This Been Tested?
- [ ] I have updated at least one of the `examples/*` to demonstrate and validate my change(s)
- [ ] I have tested and validated these changes using one or more of the provided `examples/*` projects

- [x] I have executed `pre-commit run -a` on my pull request

### CODE REVIEW

**Review by Debayan001 — APPROVED** [review]
done

**Comment by Debayan001** [comment]
done

**Review by lawrenceklh — APPROVED** [review]

**Comment by erpel** [comment]
I just got the "AccessControlListNotSupported: The bucket does not allow ACLs" message while creating a bucket using code that had worked multiple times in the past.
In this case, the settings were acl = "private" and   object_ownership = "BucketOwnerEnforced".
It might be that this combination does not make sense but it seems to sometimes work and sometimes not, depending on the order of the creation. For the situation I encountered, forcing `aws_s3_bucket_acl` to be created before `aws_s3_bucket_ownership_controls` resolved it.

I assume with this change merged some settings that may have worked in the past will reliably fail - I want to try and verify this. It might be worth noting in release notes if this goes forward.

**Comment by antonbabenko** [comment]
Thank you @PavloPavlichenko for this discovery and fix :)

**Comment by antonbabenko** [comment]
This PR is included in version 3.8.1 :tada:

**Pull request merged**
