### PR TITLE
feat!: Added support for date-based partitioning. Bump AWS provider version to 5.x and Terraform to 1.0

### PR DESCRIPTION
**Pull request by EreminAnton**
## Description
Add optional target_object_key_format configuration block to support [automatic date-based partitioning](https://docs.aws.amazon.com/AmazonS3/latest/userguide/ServerLogs.html#server-log-keyname-format). This functionality was released in [5.27.0](https://github.com/hashicorp/terraform-provider-aws/releases/tag/v5.27.0) version of AWS provider. 

## Motivation and Context
To leverage the new functionality of access logging.

## Breaking Changes
As I understand it, this pins the provider's version to 5.27.0 but offers a significant update in access logs partitioning.

## How Has This Been Tested?
- [x] I have updated at least one of the `examples/*` to demonstrate and validate my change(s)
- [x] I have tested and validated these changes using one or more of the provided `examples/*` projects
I deployed every possible combination of the target_object_key_format configuration, placed objects, and waited until access logs arrived in the required format.
- [x] I have executed `pre-commit run -a` on my pull request

### CODE REVIEW

**Comment by undeadops** [comment]
I was about to submit a patch for this as well, but thought I should look at open PRs first.  Good thing I did, saved me the effort.

**Review by antonbabenko — CHANGES_REQUESTED** [review]
Please update versions.tf everywhere to require the version of AWS provider 5.27 or newer.

**Comment by EreminAnton** [comment]
Hello! I have updated versions.tf. However, the pre-commit Terraform wrapper with for_each in the module has resulted in numerous changes in the /wrappers directory. I'm unsure if this is the expected outcome.

**Review by antonbabenko — APPROVED** [review]

**Comment by antonbabenko** [comment]
This PR is included in version 4.0.0 :tada:

**Pull request merged**
