### PR TITLE
feat: Add warpper only allows tags to be overwrite in a natural way

### PR DESCRIPTION
**Pull request by teochenglim**
## Description
That's prefect for wrapper modules, we will be using it in production. However most of time we would have some tag is for the same departments, but custom tag for individual.

## Motivation and Context
allow more flexible aws tags

## Breaking Changes
N/A

## How Has This Been Tested?
- [x] I have updated at least one of the `examples/*` to demonstrate and validate my change(s)
- [x] I have tested and validated these changes using one or more of the provided `examples/*` projects

- [ ] I have executed `pre-commit run -a` on my pull request

### CODE REVIEW

**Comment by teochenglim** [comment]
@antonbabenko 
thank you for your youtube video https://www.youtube.com/watch?v=j4qoL0B-yIY
a minor improvement you can make.

**Comment by antonbabenko** [comment]
Wrappers are very logic-less on purpose. Wrappers are generated by [pre-commit-terraform hooks](https://github.com/antonbabenko/pre-commit-terraform#terraform_wrapper_module_for_each).

To avoid overriding, you must specify tags without using `defaults`.

**Comment by teochenglim** [comment]
Hi @antonbabenko 

I would like to further elaborate my point for example the key is the same "Team", but it should be overwrite in individual bucket and yet, another tag shall not disappear.

```code
  defaults = {
    tags = {
        Team = "data"
        another = "another tag"
    }
  }

  items = {
    bucket1 = {
      bucket = "bucket1"
    }
    bucket2 = {
      bucket = "bucket2"
      tags = {
        Secure = "probably"
        Team = "data-devops"
      }
    }
  }
```

**Comment by teochenglim** [comment]
@antonbabenko  
now i get it, our implementation intention is totally opposite.

**Pull request closed without merging**
