### PR TITLE
feat: Updated S3 Bucket Block Public Access and ACL(Object Ownership) defaults to work since April 2023

### PR DESCRIPTION
**Pull request by yoyoman21**
## Description
  Modified the Variables related to block s3 public access and changed the default value of Object Ownership according to latest aws s3 bucket update.

## Motivation and Context
   i)Need to change It due to the recent s3 bucket update by aws from April 2023.Following is the link describing the change from aws:- https://aws.amazon.com/blogs/aws/heads-up-amazon-s3-security-changes-are-coming-in-april-of-2023/
   
Fixes https://github.com/terraform-aws-modules/terraform-aws-s3-bucket/issues/223
Fixes https://github.com/terraform-aws-modules/terraform-aws-s3-bucket/issues/224

## How Has This Been Tested?
- [x] I have updated at least one of the `examples/*` to demonstrate and validate my change(s)
- [x] I have tested and validated these changes using one or more of the provided `examples/*` projects

- [ ] I have executed `pre-commit run -a` on my pull request

### CODE REVIEW

**Review by stephendayext — APPROVED** [review]
+1

**Comment by wolfedale** [comment]
+1

**Review by wolfedale — APPROVED** [review]

**Review by b13n1u — APPROVED** [review]

**Comment by r1ddl3** [comment]
@barryib @antonbabenko @dynamike @bryantbiggs Is someone who is a maintainer able to approve please?

**Comment by ferrarijefferson** [comment]
+1

**Review by ferrarijefferson — APPROVED** [review]

**Comment by good92** [comment]
https://github.com/hashicorp/terraform-provider-aws/issues/28353 Notice: S3 - Changes to Defaults (Block Public Access and ACL's) - AccessControlListNotSupported: The bucket does not allow ACLs
https://docs.aws.amazon.com/AmazonS3/latest/userguide/about-object-ownership.html April 2023 changes on new S3 creation without ACLs → bucket policy

https://docs.aws.amazon.com/AmazonS3/latest/userguide/create-bucket-faq.html

**Comment by stefan-matic** [comment]
There is still a matter of `attach_policy` throwing `Error putting S3 policy: AccessDenied: Access Denied` , which is probably related to the recent change. A workaround is explained in this [comment](https://github.com/terraform-aws-modules/terraform-aws-s3-bucket/issues/223#issuecomment-1516866800).

**Comment by antonbabenko** [comment]
This PR is included in version 3.9.0 :tada:

**Pull request merged**
